version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ranjith@02
      TZ: Asia/Kolkata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com   # pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin123      # pgAdmin login password
    ports:
      - "8090:80"   # pgAdmin UI available at http://localhost:8090
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - eureka-server

  
  auth-service:
    build: ./auth-service
    depends_on:
      - config-server
      - eureka-server
      - user-service

volumes:
  postgres_data:
  pgadmin_data: